<a href="https://colab.research.google.com/github/Pavithra2530/Numpy-Pavithra-D48/blob/main/Numpy_Pavithra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print ("Hello")

Hello


In [46]:
import numpy as np              #1


In [ ]:
np.__version__, np.show_config             #2 

('1.21.6', <function numpy.__config__.show()>)

In [47]:
def null_array(n):                  #3
    x=np.zeros(n)
    return x
print(null_array(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
x = np.array([200,50,61])                  #4
 
print("Size of the array: ",
      x.size)
 
print("Memory size of one array element in bytes: ",
      x.itemsize)

Size of the array:  3
Memory size of one array element in bytes:  8


In [ ]:
np.info(np.add)              #5

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [ ]:
arr = np.zeros(10)                   #6
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
arr1 = np.arange(10,49)        #7
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [48]:
arr2 = np.arange(1,20)          #8
print(arr2)
arr2[::-1]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1])

In [ ]:
matrix = np.arange(1,10).  reshape(3,3)                  #9
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr3 = np.array ([[1, 2], [0, 0], [ 4, 0]])                  #9
print(arr3)

[[1 2]
 [0 0]
 [4 0]]


In [ ]:
arr4 = np.nonzero(arr3)                        #10
print(arr4)

(array([0, 0, 2]), array([0, 1, 0]))


In [ ]:
identity = np.eye(3)                #11
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
random = np.random.random((3,3,3))                 #12
print(random)

[[[0.23421489 0.89131802 0.55979261]
  [0.51375417 0.5430868  0.06819856]
  [0.76339565 0.43441503 0.93629891]]

 [[0.07712813 0.54773705 0.58263933]
  [0.1831259  0.49956446 0.45076796]
  [0.73684278 0.91621982 0.86461617]]

 [[0.5285874  0.45890173 0.46713068]
  [0.77891096 0.83267985 0.1275895 ]
  [0.60550134 0.34645316 0.65329802]]]


In [ ]:
random2 = np.random.random((10,10))                ##13
print(random2) 

np.min(random2) , np.max(random2)

[[0.99402777 0.77338035 0.78771365 0.60598755 0.09413824 0.19387043
  0.4207595  0.85900311 0.28020437 0.14827708]
 [0.52336045 0.63510709 0.29527907 0.77567916 0.29868326 0.72232501
  0.43456811 0.78152276 0.93675438 0.0261032 ]
 [0.78321504 0.40407714 0.92382039 0.89310307 0.58520033 0.65200685
  0.60258006 0.71102011 0.64748145 0.37309136]
 [0.82105561 0.22416852 0.84213916 0.00779282 0.47028493 0.89431902
  0.89924418 0.12237995 0.26691042 0.67333353]
 [0.60415237 0.43570188 0.15952104 0.01116117 0.1500156  0.46437917
  0.24546154 0.20018778 0.39864626 0.80596113]
 [0.39717623 0.41845553 0.74705411 0.49541903 0.92041057 0.13920547
  0.4895598  0.40515286 0.53176718 0.5585208 ]
 [0.54713323 0.49841374 0.47629938 0.4955129  0.34260701 0.51333784
  0.55726191 0.80369155 0.85464476 0.49788869]
 [0.07971458 0.73231681 0.21745617 0.77167301 0.77660455 0.77602863
  0.1939547  0.40218213 0.05094585 0.13018528]
 [0.82132757 0.70826265 0.48384604 0.75652428 0.15550477 0.18099031
  0.23910758

(0.007792815893989724, 0.9940277742891014)

In [ ]:
f = np.random.random((3,5,6))            #14
np.mean(f)

0.5060611813994209

In [ ]:
d = np.ones((5,5))           #15
print(d)
print("two D array")
d[1:-1, 1:-1] = 0
print(d)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
two D array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
b = np.ones((4,4))             #16
print(b)
print("border filled with 0's")
b = np.pad(b, pad_width=1, mode='constant', constant_values=0)
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
border filled with 0's
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
print(0 * np.nan)              #17
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)


nan
False
False
nan
False


In [ ]:
diagonal = np.diag([1,2,3,4,5])                 #18
print(diagonal)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
checker = np.ones((3,3))              #19
print(checker)
print("Checkerboard")
pattern = np.zeros((8,8),dtype=int)
pattern[::2,::2] = 1
pattern[::2,::2] = 1
print(pattern)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Checkerboard
[[1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]]


In [ ]:
print(np.unravel_index(99,(6,7,8)))           #20

(1, 5, 3)


In [ ]:
tile = np.tile(np.array([[0,1],[1,0]]),(4,4))        #21
print(tile)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
random= np.random.random((5,5))             #22
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
After normalization:
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
color = np.dtype([("r", np.ubyte),          #23
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [ ]:
z=np.dot(np.random.rand(5,3),np.random.rand(3,2))           #24
print(z)

[[1.28608158 1.20974975]
 [1.80094488 1.67407146]
 [1.28320764 1.27740722]
 [0.71642251 0.83500497]
 [1.89160319 1.83979077]]


In [ ]:
Z = np.arange(11)            #25
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [ ]:
  print(sum(range(5),-1))           #26
from numpy import *
print(sum(range(5),-1))

10
10


In [ ]:
Z = np.arange(20)               #27
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)


[                   1                    1                    4
                   27                  256                 3125
                46656               823543             16777216
            387420489          10000000000         285311670611
        8916100448256      302875106592253    11112006825558016
   437893890380859375                    0 -2863221430593058543
  -497033925936021504  6353754964178307979]
[     0      1      2      4      8     16     32     64    128    256
    512   1024   2048   4096   8192  16384  32768  65536 131072 262144]
[False False False False False False False False False False False False
 False False False False False False False False]
[0. +0.j 0. +1.j 0. +2.j 0. +3.j 0. +4.j 0. +5.j 0. +6.j 0. +7.j 0. +8.j
 0. +9.j 0.+10.j 0.+11.j 0.+12.j 0.+13.j 0.+14.j 0.+15.j 0.+16.j 0.+17.j
 0.+18.j 0.+19.j]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]


ValueError: ignored

In [ ]:
print(np.array(0) / np.array(0))                 #28
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-120-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-120-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [ ]:
f = np.array([-5.5,3.4,1.6,-5.2,-4.3])                #29
print(f)
ff=np.copysign(np.ceil(np.abs(f)),f)
print(ff)
f1=np.abs(f)
print(f1)
f2=np.floor(f1)
print(f2)
f3=np.copysign(f2,f)
print(f3)

[-5.5  3.4  1.6 -5.2 -4.3]
[-6.  4.  2. -6. -5.]
[5.5 3.4 1.6 5.2 4.3]
[5. 3. 1. 5. 4.]
[-5.  3.  1. -5. -4.]


In [ ]:
Z1 = np.random.randint(0,10,10)            #30
print(Z1)
Z2 = np.random.randint(0,10,10)
print(Z2)
print(np.intersect1d(Z1,Z2))

[5 3 6 3 9 8 4 5 4 4]
[0 5 7 6 4 3 2 2 8 9]
[3 4 5 6 8 9]


In [ ]:
import numpy as np

In [ ]:
data = np.random.random(1000).reshape(10, 10,10) * np.nan             #31
np.seterr(all="ignore")
np.nanmedian(data, axis=[1, 2])

/usr/local/lib/python3.8/dist-packages/numpy/lib/nanfunctions.py:1119: RuntimeWarning: All-NaN slice encountered
  r, k = function_base._ureduce(a, func=_nanmedian, axis=axis, out=out,


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)         #32

False

In [ ]:
today = np.datetime64('today', 'D')                   #33
print("Today: ", today)
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(tomorrow)
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print(yesterday)

Today:  2022-12-28
2022-12-29
2022-12-27


In [ ]:
print("July, 2016")                                                    #34
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

July, 2016
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
A = np.ones(3)*1                           #35
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.negative(A,out=A)
np.divide(A,2,out=A)
np.dot(A,B)

-4.5

In [ ]:
Z = np.random.uniform(0,10,10)            #36

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))

[8. 0. 2. 1. 7. 3. 9. 1. 7. 2.]
[8. 0. 2. 1. 7. 3. 9. 1. 7. 2.]
[8. 0. 2. 1. 7. 3. 9. 1. 7. 2.]
[8 0 2 1 7 3 9 1 7 2]


In [ ]:
matrix = np.zeros((5,5))            #37
matrix += np.arange(5)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
def generate():                             #38
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
v = np.linspace(0,1,11,endpoint=False)[1:]                    #39
print(v)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [ ]:
random  = np.random.random(10)                   #40
random.sort()
print(random)

[0.13592394 0.32290557 0.37715232 0.39250931 0.56714029 0.65391481
 0.68972656 0.80626811 0.81454935 0.81642206]


In [ ]:
r = np.arange(25)                  #41
np.add.reduce(r)

300

In [ ]:
b = np.random.randint(0,3,5)              #42
n = np.random.randint(0,3,5)
print(b)
print('*'*60)
print(n)
print('*'*60)
equal = np.allclose(b,n)
print(equal)
equal = np.array_equal(b,n)
print(equal)

[0 0 0 0 1]
************************************************************
[1 1 1 2 1]
************************************************************
False
False


In [ ]:
m = np.zeros(25)                             #43
m.flags.writeable = False
m[0] = 1

ValueError: ignored

In [ ]:
z= np.random.randint(0,5,(7,5))           #44
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
print(r)
t = np.arctan2(y,x)
print(t)
polar = np.c_[r,t]
print("Polar :")
print(polar)

[4.24264069 4.12310563 1.         3.60555128 3.60555128 2.
 3.16227766]
[0.78539816 0.24497866 0.         0.5880026  0.98279372 0.
 0.32175055]
Polar :
[[4.24264069 0.78539816]
 [4.12310563 0.24497866]
 [1.         0.        ]
 [3.60555128 0.5880026 ]
 [3.60555128 0.98279372]
 [2.         0.        ]
 [3.16227766 0.32175055]]


In [ ]:
ve = np.random.random(10)         #45
print(ve)
ve[ve.argmax()] = 0
print(ve)

[0.78747191 0.38170777 0.46247653 0.13511172 0.44122064 0.60588921
 0.73520136 0.42008285 0.73948592 0.94895162]
[0.78747191 0.38170777 0.46247653 0.13511172 0.44122064 0.60588921
 0.73520136 0.42008285 0.73948592 0.        ]


In [ ]:
Z = np.zeros((5,5), [('x',float),('y',float)])               #46
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [ ]:
Y = np.random.randint(0,11,10)             #47
X = np.random.randint(11,22,10)
#print(Y.reshape(1,10))
Y = np.subtract.outer(Y,(10,1))
X = np.subtract.outer(X,(10,1)).T
C = 1/(X - Y)


ValueError: ignored

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:                   #48
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [ ]:
import sys                          #49
Z = np.arange(100)
np.set_printoptions(threshold=sys.maxsize)
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
arr = np.random.uniform(0,10,10)                           #50
scal = 5
print(arr)
arr_1 = np.abs(arr - 5)
ind = arr_1.argmin()
print('*'*60)
print(arr[ind])

[5.16530976 0.1640625  4.13102663 5.95007652 4.67410943 9.92720209
 7.56293675 5.22432232 9.1221221  3.05819792]
************************************************************
5.165309756111926


In [49]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),               #51
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-49-1867a8fce118>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),               #52


In [ ]:
a= np.random.random((100,2))                                      #52
x,y = np.atleast_2d(a[:,0], a[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

[[0.         0.52809867 0.66949897 0.88552935 0.15593884 0.57425082
  0.4611705  0.81927072 0.24095119 1.04406945 0.73491769 0.66679157
  0.45863652 0.68789926 0.77534643 0.88245132 0.54715267 0.46920269
  0.86433571 0.39729852 0.33150882 0.72132965 0.41855703 0.26399551
  0.93144351 0.2587268  0.90177661 0.60995565 0.96395678 0.34425991
  0.73719372 0.566865   0.79224153 0.77571057 0.27224269 0.17600973
  0.80358774 0.92173949 0.67890846 0.61400108 0.58682782 0.51862526
  0.36871972 0.2119187  0.39519114 0.28102728 0.77652465 0.08659343
  0.54885607 0.21360698 0.43235522 0.72884621 0.56346762 0.67659043
  0.37917244 0.83234986 0.07420938 0.55826499 0.89460917 0.57878924
  0.32891104 0.2390574  0.71299776 0.47321983 0.70115167 0.75093223
  0.45244326 0.57374135 0.9091067  0.46659875 0.86118498 0.44776632
  0.53971016 0.39850605 0.80426045 0.94646834 0.33787814 0.54601415
  0.34098484 0.32456822 0.50951596 1.00960226 0.77890944 0.21323358
  0.64565324 0.10731198 0.84715738 0.42391224 0.

In [ ]:
Z = np.arange(5, dtype=np.float32)                                      #53
Z_1 = Z.astype(np.float32, copy=False)
Z_1[0] = 2
print(Z)

[2. 1. 2. 3. 4.]


In [ ]:
from io import StringIO                           #54
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [ ]:
e = np.arange(9).reshape(3,3)                          #55
for index, value in np.ndenumerate(e):
    print(index, value)
for index in np.ndindex(e.shape):
    print(index, e[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [ ]:
x, y = np.meshgrid(np.linspace(-1,1,5), np.linspace(-1,1,5))                  #56
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(g)

[[0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.60653066 0.8824969  1.         0.8824969  0.60653066]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]]


In [ ]:
n = 5                                  #57
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

np.put(Z,11,1)
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
X = np.random.rand(5, 5)                                #58
Y = X - X.mean(axis = 1,keepdims = True)
print(Y)
X.mean(axis = 1).reshape(-1,1) == X.mean(axis = 1,keepdims =True)

[[-0.26465799  0.02822463  0.03355531  0.11118609  0.09169196]
 [ 0.01274711 -0.21406208 -0.30158194  0.14848021  0.3544167 ]
 [ 0.01369438 -0.29413747  0.11573722  0.01077643  0.15392944]
 [ 0.25495087 -0.11599339  0.3167528  -0.30063047 -0.1550798 ]
 [ 0.44224669 -0.27243414  0.0959675  -0.25653593 -0.00924412]]


array([[ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [ ]:
s = np.random.randint(0,10,(5,5))                     #59
print(s)
s_1 = s
for ind in range(5):
     s_1[:,ind].sort()
print(s_1)
print(s[(-s)[:,1].argsort()])
print(s[:,s[1,:].argsort()])

[[9 3 5 9 8]
 [3 6 0 0 5]
 [3 8 1 0 0]
 [2 4 3 0 7]
 [2 0 3 9 5]]
[[2 0 0 0 0]
 [2 3 1 0 5]
 [3 4 3 0 5]
 [3 6 3 9 7]
 [9 8 5 9 8]]
[[9 8 5 9 8]
 [3 6 3 9 7]
 [3 4 3 0 5]
 [2 3 1 0 5]
 [2 0 0 0 0]]
[[0 0 2 0 0]
 [0 1 2 3 5]
 [0 3 3 4 5]
 [9 3 3 6 7]
 [9 5 9 8 8]]


In [ ]:
twod = np.random.randint(0,3,(3,10))                        #60
twod[:,1] = 0
twod = twod.astype(bool)
print(twod)
(twod).any(axis = 0)

[[False False  True  True  True  True  True  True  True  True]
 [False False  True  True  True  True False  True False  True]
 [ True False False  True  True  True False False  True  True]]


array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
x = np.random.uniform(1, 12, 5)                     #61
v = 4
n = x.flat[np.abs(x - v).argmin()]
print(n)

2.29233430264362


In [ ]:
A = np.arange(3).reshape(3,1)                     #62
B = np.arange(3).reshape(1,3)
print(A)
print(B)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print("sum :")
print(it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]
sum :
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
class Namedarray(np.ndarray):                           #63
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [ ]:
Z = np.ones(10)                                                     #64
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)


[2. 4. 3. 2. 4. 4. 2. 3. 3. 3.]


In [ ]:
X = [1,2,3,4,5,6]                                     #65
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [ ]:
w,h = 16,16                                         #66
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


In [ ]:
A = np.random.randint(0,5,(3,4,3,4))                        #67
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[23 15 27 23]
 [22 31 34 29]
 [26 21 31 29]]


In [ ]:
D = np.random.uniform(0,1,100)                          #68
S = np.random.randint(0,5,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.52461971 0.44376801 0.56886421 0.50591807 0.52525699]


In [ ]:
A = np.random.randint(0,5,(3,3))                         #69
B= np.random.randint(0,5,(3,3))
np.diag(np.dot(A, B))

array([ 8, 16, 17])

In [ ]:
Z = np.array([1,2,3,4,5])                                  #70
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::4] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [ ]:
A = np.ones((5,5,3))                                           #71
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [ ]:
Arr = np.arange(25).reshape(5,5)                         #72
Arr[[0,1]] = Arr[[1,0]]
print(Arr)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
faces = np.random.randint(0,100,(10,3))                          #73
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 4, 21) ( 4, 72) ( 8, 42) ( 8, 73) (15, 43) (15, 57) (16, 24) (16, 74)
 (17, 43) (17, 62) (21, 72) (24, 74) (32, 51) (32, 75) (34, 53) (34, 65)
 (42, 50) (42, 56) (42, 66) (42, 73) (43, 57) (43, 62) (49, 52) (49, 55)
 (50, 66) (51, 75) (52, 55) (53, 65) (56, 73)]


In [ ]:
C = np.bincount([1,1,2,3,4,4,6])                               #74  
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [ ]:
def moving_average(a, n=3) :                         #75
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [ ]:
def rolling(a, window):                                                 #76
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
Z = np.random.randint(0,2,100)                                     #77
print ('original: ')
print (Z)
print('Negating a boolean: ')
print(np.logical_not(Z, out=Z))
Z = np.random.uniform(-1.0,1.0,10)
print ('original: ')
print (Z)
print ('Change the sign of float inplace: ')
print(np.negative(Z, out=Z))

original: 
[0 1 0 0 1 1 0 1 0 1 0 0 0 0 1 1 1 1 1 0 0 0 1 0 0 1 0 1 0 1 1 0 0 1 1 0 0
 0 0 0 0 1 0 1 1 0 0 1 1 0 1 0 1 1 0 0 1 0 0 1 0 0 1 1 1 1 0 1 1 0 1 0 1 0
 0 1 0 1 1 0 0 0 1 1 0 0 1 1 1 0 0 1 1 1 0 1 1 1 0 0]
Negating a boolean: 
[1 0 1 1 0 0 1 0 1 0 1 1 1 1 0 0 0 0 0 1 1 1 0 1 1 0 1 0 1 0 0 1 1 0 0 1 1
 1 1 1 1 0 1 0 0 1 1 0 0 1 0 1 0 0 1 1 0 1 1 0 1 1 0 0 0 0 1 0 0 1 0 1 0 1
 1 0 1 0 0 1 1 1 0 0 1 1 0 0 0 1 1 0 0 0 1 0 0 0 1 1]
original: 
[-0.35165689  0.497226   -0.6049564  -0.83493973 -0.04360558 -0.78552422
 -0.3534071  -0.4685363   0.9141099  -0.50232803]
Change the sign of float inplace: 
[ 0.35165689 -0.497226    0.6049564   0.83493973  0.04360558  0.78552422
  0.3534071   0.4685363  -0.9141099   0.50232803]


In [ ]:
def distance(P0, P1, p):                                               #78    
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[10.45493745  1.92512121  9.6457064   1.51121594  6.94658249  3.49691725
  9.01030723 11.57042431  3.18186022 10.43483896]


In [ ]:
P0 = np.random.uniform(-10, 10, (5,2))                            #79
P1 = np.random.uniform(-10,10,(5,2))
p = np.random.uniform(-10, 10, (5,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 0.54655279  1.02943241  6.84494194 15.92878556  5.25627172]
 [ 7.32425109  2.60559391  4.2429599   7.38686697  1.58368115]
 [ 0.70174377  0.27925134  7.47976975 15.57078581  4.08076329]
 [10.28629086  0.10709351  6.5017474   7.25334443  1.63162893]
 [ 9.79786903  8.86356279  2.61016184  1.04056035  3.84640037]]


In [44]:
def cartesian(arrays):                                           #80
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [ ]:
Z = np.arange(1,15,dtype=int)                       #81
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
R = rolling(Z, 4)
print ('original: ')
print (Z)
print ('after strides: ')
print(R)

original: 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
after strides: 
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [ ]:
Z = np.random.uniform(0,1,(10,10))                        #82
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print (rank)

10


In [ ]:
f = np.random.randint(0,10,50)                                 #83
print (f)
print('rank:', np.bincount(f).argmax())

[3 6 0 4 1 6 2 9 5 9 6 4 0 0 7 5 7 1 3 3 9 1 5 2 2 8 4 3 1 8 3 5 3 9 6 4 9
 0 5 3 1 0 2 6 2 4 5 1 9 1]
rank: 1


In [ ]:
Z = np.random.randint(0,5,(10,10))                         #84
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
b = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(b)

[[[[4 1 3]
   [0 2 3]
   [3 1 3]]

  [[1 3 0]
   [2 3 2]
   [1 3 1]]

  [[3 0 4]
   [3 2 1]
   [3 1 3]]

  [[0 4 0]
   [2 1 2]
   [1 3 4]]

  [[4 0 4]
   [1 2 0]
   [3 4 1]]

  [[0 4 3]
   [2 0 4]
   [4 1 3]]

  [[4 3 3]
   [0 4 1]
   [1 3 0]]

  [[3 3 4]
   [4 1 4]
   [3 0 2]]]


 [[[0 2 3]
   [3 1 3]
   [3 0 1]]

  [[2 3 2]
   [1 3 1]
   [0 1 2]]

  [[3 2 1]
   [3 1 3]
   [1 2 1]]

  [[2 1 2]
   [1 3 4]
   [2 1 1]]

  [[1 2 0]
   [3 4 1]
   [1 1 0]]

  [[2 0 4]
   [4 1 3]
   [1 0 1]]

  [[0 4 1]
   [1 3 0]
   [0 1 1]]

  [[4 1 4]
   [3 0 2]
   [1 1 3]]]


 [[[3 1 3]
   [3 0 1]
   [0 0 3]]

  [[1 3 1]
   [0 1 2]
   [0 3 0]]

  [[3 1 3]
   [1 2 1]
   [3 0 3]]

  [[1 3 4]
   [2 1 1]
   [0 3 2]]

  [[3 4 1]
   [1 1 0]
   [3 2 4]]

  [[4 1 3]
   [1 0 1]
   [2 4 0]]

  [[1 3 0]
   [0 1 1]
   [4 0 2]]

  [[3 0 2]
   [1 1 3]
   [0 2 1]]]


 [[[3 0 1]
   [0 0 3]
   [3 4 3]]

  [[0 1 2]
   [0 3 0]
   [4 3 4]]

  [[1 2 1]
   [3 0 3]
   [3 4 4]]

  [[2 1 1]
   [0 3 2]
   [4 4 0]]

  [[1 1 0]
   

In [ ]:
class Symetric(np.ndarray):                                  #85
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)
S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0  5  4 14  8]
 [ 5  7  9 14 10]
 [ 4  9  3 42 13]
 [14 14 42  2  6]
 [ 8 10 13  6  9]]


In [ ]:
p, n = 10, 20                           #86
a = np.ones((p,n,n))
b = np.ones((p,n,1))
shape = np.tensordot(a, b, axes=[[0, 2], [0, 1]])
print(shape)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [5]:
Z = np.ones((16,16))                               #87
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print ('input array')
print (Z)
print ('block sum')
print (S)

input array
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
block sum
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [7]:
def iterate(Z):                                                      #88
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z
    Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [11]:
Z = np.arange(10000)                                 #89
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9995 9999 9996 9997 9998]


In [12]:
def cartesian(arrays):                                         #90
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [14]:
Z = np.array([("Hello", 2.5, 4),                            #91
              ("World", 3.6, 3)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 4) (b'World', 3.6, 3)]


In [18]:
x = np.random.rand(int(5e7))                             #92

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)
print(x)

2.91 s ± 279 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
86.8 ms ± 1.46 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
78.3 ms ± 1.38 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
[0.60000884 0.30054314 0.88820751 ... 0.9669234  0.80960656 0.32019505]


In [19]:
A = np.random.randint(0,5,(8,3))                                   #93
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 5 7]


In [22]:
Z = np.random.randint(0,5,(10,3))                                 #94
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[2 1 0]
 [4 3 3]
 [0 0 1]
 [0 0 1]
 [2 2 4]
 [3 4 1]
 [4 4 3]
 [3 4 0]
 [3 4 1]
 [4 4 2]]
[[2 1 0]
 [4 3 3]
 [0 0 1]
 [0 0 1]
 [2 2 4]
 [3 4 1]
 [4 4 3]
 [3 4 0]
 [3 4 1]
 [4 4 2]]


In [24]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)                       #95
print(np.unpackbits(I[:, np.newaxis], axis=1))


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [25]:
Z = np.random.randint(0,2,(6,3))                                            #96
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [1 1 0]]


In [36]:
A = np.random.uniform(0,1,10)                                            #97
B = np.random.uniform(0,1,10)
print(A)
print(B)
np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B)  # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)  # np.outer(A, B)

[0.14496738 0.45728159 0.29103103 0.52240922 0.04151327 0.30465558
 0.92104362 0.72035512 0.98593589 0.46814772]
[0.27600658 0.91257833 0.31034598 0.11874379 0.33171158 0.97433424
 0.98275008 0.6543126  0.68137798 0.74713702]


array([[0.04001195, 0.13229409, 0.04499004, 0.01721398, 0.04808736,
        0.14124668, 0.14246671, 0.09485398, 0.09877758, 0.1083105 ],
       [0.12621273, 0.41730527, 0.1419155 , 0.05429935, 0.1516856 ,
        0.44554511, 0.44939352, 0.29920511, 0.31158161, 0.34165201],
       [0.08032648, 0.26558861, 0.09032031, 0.03455813, 0.09653836,
        0.2835615 , 0.28601077, 0.19042527, 0.19830214, 0.21744006],
       [0.14418839, 0.47673934, 0.1621276 , 0.06203285, 0.17328919,
        0.50900119, 0.51339771, 0.34181894, 0.35595814, 0.39031127],
       [0.01145794, 0.03788411, 0.01288348, 0.00492944, 0.01377043,
        0.0404478 , 0.04079717, 0.02716266, 0.02828623, 0.0310161 ],
       [0.08408695, 0.27802208, 0.09454863, 0.03617596, 0.10105778,
        0.29683636, 0.29940029, 0.19933998, 0.2075856 , 0.22761946],
       [0.2542141 , 0.84052445, 0.28584219, 0.10936821, 0.30552083,
        0.89740434, 0.90515569, 0.60265045, 0.62757884, 0.68814579],
       [0.19882276, 0.65738047, 0.2235593

In [41]:
phi = np.arange(0, 10*np.pi, 0.1)                                             #98
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)
print(x_int)
print(y_int)

[ 0.00000000e+00 -3.73131229e-01 -2.59817608e+00 -3.26212050e+00
 -2.18442687e+00 -2.98929946e-02  2.42923642e+00  4.54913599e+00
  5.92318348e+00  6.35117933e+00  5.82369277e+00  4.46259540e+00
  2.47320794e+00  1.09577220e-01 -2.36575300e+00 -4.71261671e+00
 -6.72701769e+00 -8.25541575e+00 -9.18486120e+00 -9.46381505e+00
 -9.11085788e+00 -8.12875279e+00 -6.63306046e+00 -4.69271059e+00
 -2.44736165e+00 -2.05444585e-02  2.46101146e+00  4.86841760e+00
  7.08937968e+00  9.02539126e+00  1.05948609e+01  1.17357250e+01
  1.24068974e+01  1.25885805e+01  1.22815267e+01  1.15053927e+01
  1.02963689e+01  8.70429550e+00  6.78948686e+00  4.61716636e+00
  2.25853448e+00 -1.98731680e-01 -2.68040566e+00 -5.11543300e+00
 -7.41973991e+00 -9.53891040e+00 -1.14237629e+01 -1.29919305e+01
 -1.42355069e+01 -1.51243232e+01 -1.56061571e+01 -1.57219415e+01
 -1.54217066e+01 -1.47579136e+01 -1.37255236e+01 -1.23634834e+01
 -1.07024632e+01 -8.78327367e+00 -6.65029558e+00 -4.35514246e+00
 -1.94290275e+00  5.28038

In [42]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],                                             #99
[2.0, 0.0, 1.0, 1.0],
[1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [43]:
X = np.random.randn(100) # random 1D array                                          #100
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.34739137  0.00144956]
